Sync Lyrics
-----------

OK, it's finally time to start the graphics.

1. Open Karaoke Builder Studio.
2. If it opened an existing project, hit the New button.
3. Paste your lyrics into the big text box.
   
   .. image:: images/qs-kbs-1.png
      :alt: Screenshot of Karaoke Builder Studio, showing right-click menu in main text box with Paste selected

4. Click on each block of text and make sure all the lines are visible and text is not going off screen. If any is, add line breaks as needed.
5. Click the audio button and add your audio file (either the full audio or vocal stem, not the instrumental).
6. Hit the Sync button. It will immediately start playing the music.
   
   .. image:: images/qs-kbs-2.png
      :alt: Screenshot of Karaoke Builder Studio, showing the sync button

7. The next word/syllable is marked in orange. Hit space on your keyboard when the audio for it plays.
   
   .. image:: images/qs-kbs-3.png
      :alt: Screenshot of the sync window of Karaoke Builder Studio

8. Click the audio button and switch to the instrumental version you will use for your final track.

There are some other features in the sync UI, and a ton of editing and styling options we haven't touched, but this is a *Quick* Start, so those are the essentials.

