Sync Lyrics
-----------

OK, it's finally time to start the graphics.

1. Open Karaoke Builder Studio.
2. If it opened an existing project, hit the New button.
3. Paste your lyrics into the big text box.
4. Click on each block of text and make sure all the lines are visible and text is not going off screen. If any is, add line breaks as needed.
5. Click the audio button and add your audio file (either the full audio or vocal stem, not the instrumental).
6. Hit the Sync button. It will immediately start playing the music.
7. The next word/syllable is marked in orange. Hit space on your keyboard when the audio for it plays.

There are some other features in the sync UI, but this is a *Quick* Start, so those are the essentials.

