Format Lyrics
-------------

Now we need lyrics in a good format for karaoke.

Find accurate lyrics 
^^^^^^^^^^^^^^^^^^^^

If there's official lyrics on the band's Bandcamp or YouTube video description, great, use those. If there's a devoted fan community site (e.g. `Weird Al Wiki <https://weirdal.fandom.com/wiki/Weird_Al_Wiki>`_ or `TMBW <https://tmbw.net/wiki/Main_Page>`_), also a great resource. Failing that, `Genius <https://genius.com>`_ usually does ok.

Listen to the song while reading through the lyrics and make sure things match up. Sometimes a line needs to be doubled, or an ad-lib needs to be added. The more accurate it is, the easier it will be to sync, and the less editing will be needed after.

Organize into pages
^^^^^^^^^^^^^^^^^^^

Only so many lines of text can be shown on a screen at a time so it helps to split in logical places. Usually lyrics sites will at least split between verses and chorus, but if e.g. a verse is 8 lines, you may want to split that into two blocks of 4. Some lines may be very long and need split as well.

Add syllable marks
^^^^^^^^^^^^^^^^^^

This is technically optional, but it really does help make the sync look more accurate, especially for sustained words. Add a slash ("/") between syllables to have them operate as separate units during syncing.

It may be helpful to use the Magic Slashes feature on `The Tüül <https://the-tuul.com/>`_: Paste your lyrics into the lyrics tab then start adding slashes as normal. If it sees a word repeated later in the lyrics, it will automatically add slashes to the same place in that instance of the word.
