Separate Audio
--------------

If you already have a backing track, feel free to skip this part (but don't take the audio from commercial karaoke, see :doc:`original_audio`).

1. Find the highest quality version of the track you can. If you can get flac from Bandcamp or similar, that's your best bet.

2. Run a vocal removal model:

   a. Go to the `x-minus vocal remover page <https://x-minus.pro/ai>`_.

   b. Select the "mel-roformer" AI model, or "mel-roformer (kar)" if you want backing vocals. If these models are no longer available in the free version, you can use their "Vocal remover" or "Keep backing vocals" shortcut links to get to the best they'll offer.

   c. Drag and drop your high quality audio file.

   d. Set the format as desired and download the Instrumental and Vocal stems it generated.
